language: python

matrix:
  include:
  - os: linux
    python: "2.7"
  - os: osx
    python: "2.7"
  allow_failures:
  - os: linux
    python: "3.6"
  - os: osx
    python: "3.6"

script:
  - make test
