language: python

matrix:
  include:
  - os: linux
    python: "2.7"
  allow_failures:
  - os: linux
    python: "3.6"
  - os: osx
    python: "3.6"
  - os: osx
    python: "2.7"

install:
  - pip install -r requirements-dev.txt
script:
  - make test
